version: "3.8"

services:
  nlp-backend:
    container_name: nlp-backend
    build: .
    image: nlp-backend
    restart: unless-stopped
    environment:
      - SPRING_SERVER_PORT=${SERVER_PORT}
      - SPRING_MONGO_HOST=${MONGO_HOST}
      - SPRING_MONGO_PORT=${MONGO_PORT}
      - SPRING_MONGO_URI=${MONGO_URI}
      - SPRING_JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SPRING_YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - SPRING_PROFILES_ACTIVE=${PROFILES_ACTIVE}
      - SPRING_MODELS_APP_DESTINATION_PATH=${MODELS_APP_DESTINATION_PATH}
      - SPRING_TF_SERVING_CONFIG_FILE_NAME=${TF_SERVING_CONFIG_FILE_NAME}
      - SPRING_TF_SERVING_HOST=${TF_SERVING_HOST}
      - SPRING_TF_SERVING_PORT=${TF_SERVING_PORT}
      - SPRING_YT_VIDEOS_MAX_RESULTS=${YT_VIDEOS_MAX_RESULTS}
      - SPRING_YT_COMMENTS_MAX_RESULTS=${YT_COMMENTS_MAX_RESULTS}
      - SPRING_YT_CHANNEL_VIDEOS_MAX_RESULTS=${YT_CHANNEL_VIDEOS_MAX_RESULTS}
    volumes:
      - type: bind
        source: ${MODELS_HOST_PATH}
        target: ${MODELS_APP_DESTINATION_PATH}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - nlp-network

  mongo:
    container_name: nlp-mongo
    image: mongo:6.0.2
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - nlp-network

  tf-serving:
    container_name: nlp-tf-serving
    image: tensorflow/serving:2.12.1
    restart: always
    volumes:
      - type: bind
        source: ${MODELS_HOST_PATH}
        target: ${MODELS_APP_DESTINATION_PATH}
    ports:
      - ${TF_SERVING_PORT}:${TF_SERVING_PORT}
    command:
      - --model_config_file=${MODELS_APP_DESTINATION_PATH}${TF_SERVING_CONFIG_FILE_NAME}
      - --model_config_file_poll_wait_seconds=${TF_SERING_CONFIG_REFRESH_INTERVAL_SECONDS}
    networks:
      - nlp-network

networks:
  nlp-network:
    name: nlp-network
    driver: bridge