// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tfmodels.proto

package it.nlp.backend.textAnalysis.protos;

public interface ModelServerConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.serving.ModelServerConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tensorflow.serving.ModelConfigList model_config_list = 1;</code>
   * @return Whether the modelConfigList field is set.
   */
  boolean hasModelConfigList();
  /**
   * <code>.tensorflow.serving.ModelConfigList model_config_list = 1;</code>
   * @return The modelConfigList.
   */
  it.nlp.backend.textAnalysis.protos.ModelConfigList getModelConfigList();
  /**
   * <code>.tensorflow.serving.ModelConfigList model_config_list = 1;</code>
   */
  it.nlp.backend.textAnalysis.protos.ModelConfigListOrBuilder getModelConfigListOrBuilder();
}
