// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tfmodels.proto

package it.nlp.backend.textAnalysis.protos;

public interface ModelConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.serving.ModelConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string base_path = 2;</code>
   * @return The basePath.
   */
  java.lang.String getBasePath();
  /**
   * <code>string base_path = 2;</code>
   * @return The bytes for basePath.
   */
  com.google.protobuf.ByteString
      getBasePathBytes();

  /**
   * <code>string model_platform = 3;</code>
   * @return The modelPlatform.
   */
  java.lang.String getModelPlatform();
  /**
   * <code>string model_platform = 3;</code>
   * @return The bytes for modelPlatform.
   */
  com.google.protobuf.ByteString
      getModelPlatformBytes();
}
