// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tfmodels.proto

package it.nlp.backend.textAnalysis.protos;

public final class ModelServerConfigProtos {
  private ModelServerConfigProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_serving_ModelConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_serving_ModelConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_serving_ModelConfigList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_serving_ModelConfigList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_serving_ModelServerConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_serving_ModelServerConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016tfmodels.proto\022\022tensorflow.serving\"F\n\013" +
      "ModelConfig\022\014\n\004name\030\001 \001(\t\022\021\n\tbase_path\030\002" +
      " \001(\t\022\026\n\016model_platform\030\003 \001(\t\"B\n\017ModelCon" +
      "figList\022/\n\006config\030\001 \003(\0132\037.tensorflow.ser" +
      "ving.ModelConfig\"S\n\021ModelServerConfig\022>\n" +
      "\021model_config_list\030\001 \001(\0132#.tensorflow.se" +
      "rving.ModelConfigListB?\n\"it.nlp.backend." +
      "textAnalysis.protosB\027ModelServerConfigPr" +
      "otosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tensorflow_serving_ModelConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_serving_ModelConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_serving_ModelConfig_descriptor,
        new java.lang.String[] { "Name", "BasePath", "ModelPlatform", });
    internal_static_tensorflow_serving_ModelConfigList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_serving_ModelConfigList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_serving_ModelConfigList_descriptor,
        new java.lang.String[] { "Config", });
    internal_static_tensorflow_serving_ModelServerConfig_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tensorflow_serving_ModelServerConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_serving_ModelServerConfig_descriptor,
        new java.lang.String[] { "ModelConfigList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
