// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tfmodels.proto

package it.nlp.backend.emotionAnalysis.protos;

/**
 * Protobuf type {@code tensorflow.serving.ModelConfig}
 */
public final class ModelConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.serving.ModelConfig)
    ModelConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ModelConfig.newBuilder() to construct.
  private ModelConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ModelConfig() {
    name_ = "";
    basePath_ = "";
    modelPlatform_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ModelConfig();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return it.nlp.backend.emotionAnalysis.protos.ModelServerConfigProtos.internal_static_tensorflow_serving_ModelConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return it.nlp.backend.emotionAnalysis.protos.ModelServerConfigProtos.internal_static_tensorflow_serving_ModelConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            it.nlp.backend.emotionAnalysis.protos.ModelConfig.class, it.nlp.backend.emotionAnalysis.protos.ModelConfig.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BASE_PATH_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object basePath_ = "";
  /**
   * <code>string base_path = 2;</code>
   * @return The basePath.
   */
  @java.lang.Override
  public java.lang.String getBasePath() {
    java.lang.Object ref = basePath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      basePath_ = s;
      return s;
    }
  }
  /**
   * <code>string base_path = 2;</code>
   * @return The bytes for basePath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBasePathBytes() {
    java.lang.Object ref = basePath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      basePath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODEL_PLATFORM_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object modelPlatform_ = "";
  /**
   * <code>string model_platform = 3;</code>
   * @return The modelPlatform.
   */
  @java.lang.Override
  public java.lang.String getModelPlatform() {
    java.lang.Object ref = modelPlatform_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modelPlatform_ = s;
      return s;
    }
  }
  /**
   * <code>string model_platform = 3;</code>
   * @return The bytes for modelPlatform.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelPlatformBytes() {
    java.lang.Object ref = modelPlatform_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modelPlatform_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(basePath_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, basePath_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(modelPlatform_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, modelPlatform_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(basePath_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, basePath_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(modelPlatform_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, modelPlatform_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof it.nlp.backend.emotionAnalysis.protos.ModelConfig)) {
      return super.equals(obj);
    }
    it.nlp.backend.emotionAnalysis.protos.ModelConfig other = (it.nlp.backend.emotionAnalysis.protos.ModelConfig) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getBasePath()
        .equals(other.getBasePath())) return false;
    if (!getModelPlatform()
        .equals(other.getModelPlatform())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + BASE_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getBasePath().hashCode();
    hash = (37 * hash) + MODEL_PLATFORM_FIELD_NUMBER;
    hash = (53 * hash) + getModelPlatform().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static it.nlp.backend.emotionAnalysis.protos.ModelConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.nlp.backend.emotionAnalysis.protos.ModelConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.nlp.backend.emotionAnalysis.protos.ModelConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.nlp.backend.emotionAnalysis.protos.ModelConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.nlp.backend.emotionAnalysis.protos.ModelConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static it.nlp.backend.emotionAnalysis.protos.ModelConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static it.nlp.backend.emotionAnalysis.protos.ModelConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static it.nlp.backend.emotionAnalysis.protos.ModelConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static it.nlp.backend.emotionAnalysis.protos.ModelConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static it.nlp.backend.emotionAnalysis.protos.ModelConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static it.nlp.backend.emotionAnalysis.protos.ModelConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static it.nlp.backend.emotionAnalysis.protos.ModelConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(it.nlp.backend.emotionAnalysis.protos.ModelConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tensorflow.serving.ModelConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.serving.ModelConfig)
      it.nlp.backend.emotionAnalysis.protos.ModelConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.nlp.backend.emotionAnalysis.protos.ModelServerConfigProtos.internal_static_tensorflow_serving_ModelConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.nlp.backend.emotionAnalysis.protos.ModelServerConfigProtos.internal_static_tensorflow_serving_ModelConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.nlp.backend.emotionAnalysis.protos.ModelConfig.class, it.nlp.backend.emotionAnalysis.protos.ModelConfig.Builder.class);
    }

    // Construct using it.nlp.backend.emotionAnalysis.protos.ModelConfig.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      basePath_ = "";
      modelPlatform_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return it.nlp.backend.emotionAnalysis.protos.ModelServerConfigProtos.internal_static_tensorflow_serving_ModelConfig_descriptor;
    }

    @java.lang.Override
    public it.nlp.backend.emotionAnalysis.protos.ModelConfig getDefaultInstanceForType() {
      return it.nlp.backend.emotionAnalysis.protos.ModelConfig.getDefaultInstance();
    }

    @java.lang.Override
    public it.nlp.backend.emotionAnalysis.protos.ModelConfig build() {
      it.nlp.backend.emotionAnalysis.protos.ModelConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public it.nlp.backend.emotionAnalysis.protos.ModelConfig buildPartial() {
      it.nlp.backend.emotionAnalysis.protos.ModelConfig result = new it.nlp.backend.emotionAnalysis.protos.ModelConfig(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(it.nlp.backend.emotionAnalysis.protos.ModelConfig result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.basePath_ = basePath_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.modelPlatform_ = modelPlatform_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof it.nlp.backend.emotionAnalysis.protos.ModelConfig) {
        return mergeFrom((it.nlp.backend.emotionAnalysis.protos.ModelConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(it.nlp.backend.emotionAnalysis.protos.ModelConfig other) {
      if (other == it.nlp.backend.emotionAnalysis.protos.ModelConfig.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getBasePath().isEmpty()) {
        basePath_ = other.basePath_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getModelPlatform().isEmpty()) {
        modelPlatform_ = other.modelPlatform_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              basePath_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              modelPlatform_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object basePath_ = "";
    /**
     * <code>string base_path = 2;</code>
     * @return The basePath.
     */
    public java.lang.String getBasePath() {
      java.lang.Object ref = basePath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        basePath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string base_path = 2;</code>
     * @return The bytes for basePath.
     */
    public com.google.protobuf.ByteString
        getBasePathBytes() {
      java.lang.Object ref = basePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        basePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string base_path = 2;</code>
     * @param value The basePath to set.
     * @return This builder for chaining.
     */
    public Builder setBasePath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      basePath_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string base_path = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBasePath() {
      basePath_ = getDefaultInstance().getBasePath();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string base_path = 2;</code>
     * @param value The bytes for basePath to set.
     * @return This builder for chaining.
     */
    public Builder setBasePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      basePath_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object modelPlatform_ = "";
    /**
     * <code>string model_platform = 3;</code>
     * @return The modelPlatform.
     */
    public java.lang.String getModelPlatform() {
      java.lang.Object ref = modelPlatform_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modelPlatform_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string model_platform = 3;</code>
     * @return The bytes for modelPlatform.
     */
    public com.google.protobuf.ByteString
        getModelPlatformBytes() {
      java.lang.Object ref = modelPlatform_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelPlatform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string model_platform = 3;</code>
     * @param value The modelPlatform to set.
     * @return This builder for chaining.
     */
    public Builder setModelPlatform(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      modelPlatform_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string model_platform = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearModelPlatform() {
      modelPlatform_ = getDefaultInstance().getModelPlatform();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string model_platform = 3;</code>
     * @param value The bytes for modelPlatform to set.
     * @return This builder for chaining.
     */
    public Builder setModelPlatformBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      modelPlatform_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.serving.ModelConfig)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.serving.ModelConfig)
  private static final it.nlp.backend.emotionAnalysis.protos.ModelConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new it.nlp.backend.emotionAnalysis.protos.ModelConfig();
  }

  public static it.nlp.backend.emotionAnalysis.protos.ModelConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ModelConfig>
      PARSER = new com.google.protobuf.AbstractParser<ModelConfig>() {
    @java.lang.Override
    public ModelConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ModelConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ModelConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public it.nlp.backend.emotionAnalysis.protos.ModelConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

